
DROP TABLE UserInfo CASCADE CONSTRAINTS;

DROP TABLE Student CASCADE CONSTRAINTS;
DROP TABLE Professor CASCADE CONSTRAINTS;
DROP TABLE TA CASCADE CONSTRAINTS;

DROP TABLE Topic CASCADE CONSTRAINTS;
DROP TABLE Course CASCADE CONSTRAINTS;
DROP TABLE Enrolled CASCADE CONSTRAINTS;
DROP TABLE Assisting CASCADE CONSTRAINTS;
DROP TABLE TopicPerCourse CASCADE CONSTRAINTS;

DROP TABLE Exercise CASCADE CONSTRAINTS;
DROP TABLE Question CASCADE CONSTRAINTS;
DROP TABLE ExerciseQuestion CASCADE CONSTRAINTS;
DROP TABLE Answer CASCADE CONSTRAINTS;
DROP TABLE Attempt CASCADE CONSTRAINTS;
DROP TABLE AttemptQuestion CASCADE CONSTRAINTS;
DROP TABLE AttemptAnswer CASCADE CONSTRAINTS;

DROP SEQUENCE userinfo_ids;
DROP SEQUENCE professor_ids;
DROP SEQUENCE ta_ids;
DROP SEQUENCE topic_ids;
DROP SEQUENCE exercise_ids;
DROP SEQUENCE answer_ids;
DROP SEQUENCE attempt_ids;

